---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secrets-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  gittokenname: '{{ .Values.git.token.name | b64enc }}'
  gittokenvalue: '{{ .Values.git.token.value | b64enc }}'
---